version: 2
updates:
  # Enable version updates for pub dependencies
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "jsb"
    labels:
      - "dependencies"
      - "dart"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      # Ignore major version updates for stable packages
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Enable version updates for example app dependencies
  - package-ecosystem: "pub"
    directory: "/example"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "jsb"
    labels:
      - "dependencies"
      - "example"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "jsb"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"